name: Deploy snapshot

on:
  push:
    branches:
      - 'release/v[0-9]+.[0-9]+.[0-9]+'

jobs:
  run-tests:
    uses: ./.github/workflows/test.yml

  deploy-snapshot:
    name: Snapshot deploy
    runs-on: ubuntu-latest
    needs:
      - run-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node environment
        uses: actions/setup-node@v3
        with:
          node-version: 14.19.3
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Generate build number
        uses: einaregilsson/build-number@v3
        with:
          token: ${{secrets.github_token}}

      - name: Create snapshot
        run: npx npm-snapshot $BUILD_NUMBER
