name: Deploy stable

on:
  push:
    branches:
      - 'main'

jobs:
  run-tests:
    uses: ./.github/workflows/test.yml

  deploy-stable:
    name: Stable deploy
    runs-on: ubuntu-latest
    needs:
      - run-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node environment
        uses: actions/setup-node@v3
        with:
          node-version: 14.19.3
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Create stable release
        run: npm publish --tag latest
